# Generated by Django 3.2 on 2021-05-07 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210507_2242'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Property',
            new_name='Building',
        ),
        migrations.RenameField(
            model_name='building',
            old_name='property',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='property',
            new_name='building',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='property',
            new_name='building',
        ),
    ]
