# Generated by Django 3.2 on 2021-07-09 10:48

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20210509_1854'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='complaint',
            managers=[
                ('reportobjects', django.db.models.manager.Manager()),
            ],
        ),
    ]
