# Generated by Django 3.2 on 2021-07-09 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_complaint_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='complaint',
            managers=[
            ],
        ),
    ]
