# Generated by Django 3.2 on 2021-07-20 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_complaint_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('videofile', models.FileField(upload_to='complaints/videos/<function Video.video_dir at 0x2ab2d3517af0>')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.complaint')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='complaints/photos/<function Photo.photo_dir at 0x2ab2d3524160>')),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.complaint')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
    ]
