# Generated by Django 3.2 on 2021-08-11 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20210811_0740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_completed',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='complaints/photos/<function Photo.photo_dir at 0x2b382d86a1f0>'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='complaints/videos/<function Video.video_dir at 0x2b382d85eb80>'),
        ),
    ]
