# Generated by Django 3.2 on 2021-11-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20211109_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='recent_reply_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='complaints/photos/<function Photo.photo_dir at 0x2ba6891cfc10>'),
        ),
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to='complaints/videos/<function Video.video_dir at 0x2ba6891cfd30>'),
        ),
    ]
